### ISSUE TITLE
App is Crashing

### ISSUE THREAD

**Issue by arshilk** [fossasia/open-event-droidgen#1799]
**Actual Behaviour**

App Crashed when i opened it.
**Expected Behaviour**

App should not Crash 

**Steps to reproduce it**

Open the open event android

**LogCat for the issue**

![screen shot 2017-07-09 at 10 21 32 pm](https://user-images.githubusercontent.com/21264401/27995960-33e55f6c-64f5-11e7-80e4-dc93f35ea36e.png)

:20:07.079 10234-10234/? I/BaseActivity: Activity onCreate: total instances 1
07-09 22:20:07.093 10234-10234/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
07-09 22:20:07.145 10234-10234/? V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
07-09 22:20:07.145 10234-10234/? V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
07-09 22:20:07.145 10234-10234/? V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
07-09 22:20:07.145 10234-10234/? V/BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
07-09 22:20:07.145 10234-10234/? V/BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
07-09 22:20:07.147 10234-10234/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f33461a
07-09 22:20:07.147 10234-10234/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@a4cf54b
07-09 22:20:07.147 10234-10234/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@8837b28
07-09 22:20:07.147 10234-10234/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@871d041
07-09 22:20:07.210 10234-10234/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@1c7f70f
07-09 22:20:07.210 10234-10234/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@404f39c
07-09 22:20:07.242 10234-10234/? D/ButterKnife: Looking up binding for org.fossasia.openevent.activities.MainActivity
07-09 22:20:07.243 10234-10234/? D/ButterKnife: HIT: Loaded binding class and constructor.
07-09 22:20:07.270 10234-10234/? D/AndroidRuntime: Shutting down VM
07-09 22:20:07.271 10234-10234/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.fossasia.openevent, PID: 10234
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.openevent/org.fossasia.openevent.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2728)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6290)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                       at org.fossasia.openevent.activities.MainActivity.setNavHeader(MainActivity.java:309)
                                                       at org.fossasia.openevent.activities.MainActivity.setupEvent(MainActivity.java:277)
                                                       at org.fossasia.openevent.activities.MainActivity.onCreate(MainActivity.java:188)
                                                       at android
**Would you like to work on the issue?**

Yes

**Comment by mahikaw** [comment]
@Arshilgenius thanks for pointing out the issue but it is a duplicate issue. Please check the recent open as well as closed issues before creating a new one. 
Also, the project is undergoing an API transformation so this is intended. Could you please close it for now?

**Comment by arshilk** [comment]
Sure.
