### ISSUE TITLE
App Crash on Selecting Description of Tracks

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-droidgen#2073]
**Actual Behaviour**

The App is crashing

**Expected Behaviour**

It should not crash

**Steps to reproduce it**

Open the app go to the Tracks Section, Open any track and try to copy the desctiption.

**LogCat for the issue**
12-31 02:48:43.442 2851-2851/org.fossasia.openevent E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.openevent, PID: 2851
                                                                      java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
                                                                          at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:357)
                                                                          at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
                                                                          at android.text.SpannableString.setSpan(SpannableString.java:46)
                                                                          at android.text.Selection.setSelection(Selection.java:76)
                                                                          at android.widget.Editor$SelectionEndHandleView.updateSelection(Editor.java:3748)
                                                                          at android.widget.Editor$HandleView.positionAtCursorOffset(Editor.java:3383)
                                                                          at android.widget.Editor$HandleView.positionAtCursorOffset(Editor.java:3367)
                                                                          at android.widget.Editor$SelectionEndHandleView.updatePosition(Editor.java:3763)
                                                                          at android.widget.Editor$HandleView.onTouchEvent(Editor.java:3503)
                                                                          at android.view.View.dispatchTouchEvent(View.java:8393)
                                                                          at android.view.View.dispatchPointerEvent(View.java:8583)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4091)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3957)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3562)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3528)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3638)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3536)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3695)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3562)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3528)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3536)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5806)
                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5745)
                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5716)
                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5896)
                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                          at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                          at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
                                                                          at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5867)
                                                                          at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5919)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Would you like to work on the issue?**

Yes!

@the-dagger @iamareebjamal

**Comment by the-dagger** [comment]
Sure, go ahead.

**Comment by iamareebjamal** [comment]
Fixed in unrelated PR
