### ISSUE TITLE
App crashes on clicking Speakers from Nav Drawer

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-droidgen#2150]
**Actual Behaviour**

App Crashes on Selecting Speakers from Navigation Drawer

**Expected Behaviour**

It should not crash

**LogCat for the issue**

FATAL EXCEPTION: main
                                                                    Process: org.fossasia.openevent, PID: 891
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.fossasia.openevent.dbutils.FilterableRealmLiveData.filter(io.reactivex.functions.Predicate)' on a null object reference
                                                                        at org.fossasia.openevent.viewmodels.SpeakersListFragmentViewModel.loadFilteredSpeakers(SpeakersListFragmentViewModel.java:44)
                                                                        at org.fossasia.openevent.viewmodels.SpeakersListFragmentViewModel.getSpeakers(SpeakersListFragmentViewModel.java:35)
                                                                        at org.fossasia.openevent.fragments.SpeakersListFragment.loadData(SpeakersListFragment.java:117)
                                                                        at org.fossasia.openevent.fragments.SpeakersListFragment.onCreateView(SpeakersListFragment.java:87)
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Would you like to work on the issue?**

Yes

**Comment by dr0pdb** [comment]
@S2606 The simple solution would be to add a null check for the filterableRealmLiveData in the line 
```if (sortType != speakersListSortType) ``` which somehow embarresingly i missed.
Thanks.
PS: Also add an null check before ```filterableRealmLiveData = RealmDataRepository.asFilterableLiveData(realmRepo.getSpeakers(sortOrderSpeaker()));``` as it only needs to be assigned if it is null.

**Comment by S2606** [comment]
@srv-twry I tried but then I get this error

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.arch.lifecycle.LiveData.observe(android.arch.lifecycle.LifecycleOwner, android.arch.lifecycle.Observer)' on a null object reference
                                                                          at org.fossasia.openevent.fragments.SpeakersListFragment.loadData(SpeakersListFragment.java:118)
                                                                          at org.fossasia.openevent.fragments.SpeakersListFragment.onCreateView(SpeakersListFragment.java:87)
                                                                          at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                          at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                          at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                          at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by dr0pdb** [comment]
Please convert the getSpeakers method to the below one and try again.
``` Java
public LiveData<List<Speaker>> getSpeakers(int sortType, String searchText) {
        setSearchText(searchText);
        if (sortType != speakersListSortType || filterableRealmLiveData == null) {
            if(filterableRealmLiveData == null) {
                filterableRealmLiveData = RealmDataRepository.asFilterableLiveData(realmRepo.getSpeakers(sortOrderSpeaker()));
            }
            speakersListSortType = sortType;
            loadFilteredSpeakers();
        } else {
            loadFilteredSpeakers();
        }
        return filterableRealmLiveData;
    }
```
