### ISSUE TITLE
app crash when pickingUp image from gallery

### ISSUE THREAD

**Issue by jindalAnuj** [fossasia/open-event-droidgen#2260]
**Actual Behaviour**

App crashes when image is picked for profile

**Expected Behaviour**

App should not crash

**Steps to reproduce it**
go to login
click profile logo
pick a image 
tada app crashed .....

**LogCat for the issue**

`java.lang.RuntimeException: An error occurred while executing doInBackground()
 at android.os.AsyncTask$3.done(AsyncTask.java:325)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=22827, uid=10533 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
 at android.os.Parcel.readException(Parcel.java:1684)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
 at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
 at android.content.ContentResolver.query(ContentResolver.java:534)
 at android.content.ContentResolver.query(ContentResolver.java:475)
 at com.yalantis.ucrop.util.FileUtils.getDataColumn(FileUtils.java:109)
 at com.yalantis.ucrop.util.FileUtils.getPath(FileUtils.java:183)
 at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:171)
 at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:90)
 at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
 at android.os.AsyncTask$2.call(AsyncTask.java:305)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 ... 4 more`

**Screenshots of the issue**

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/31108317/35472599-11b632c6-0398-11e8-9949-e7567c356775.gif)

**Would you like to work on the issue?**

Yes

**Comment by jindalAnuj** [comment]
@iamareebjamal should i start working on it should be labeled later as this serious crash need to be solved before start implementing tickets , payments ,discount code feature from api

**Comment by iamareebjamal** [comment]
Bugs are high priority, so please go on

**Comment by rishabhkalra96** [comment]
is this issue still open?

**Comment by dr0pdb** [comment]
@rishabhkalra96 In case you're still interested in this. yes it's open
