### ISSUE TITLE
App crashes on selecting Edit profile inside My Profile

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2462]
**Expected Behaviour**

This should not happen

**LogCat for the issue**

```
JNI DETECTED ERROR IN APPLICATION: JNI NewLocalRef called with pending exception java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter value
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at putString (SharedPreferencesUtil.kt:-1)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at showUserData (EditProfileActivity.java:238)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at lambda$onCreate$0$EditProfileActivity (EditProfileActivity.java:82)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onChanged ((Unknown Source):-1)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at considerNotify (LiveData.java:109)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at dispatchingValue (LiveData.java:126)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at setValue (LiveData.java:282)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at bridge$lambda$0$LiveRealmDataObject (LiveRealmDataObject.java:-1)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onChange ((Unknown Source):-1)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onChange (ProxyState.java:50)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onChange (OsObject.java:73)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onCalled (ProxyState.java:70)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onCalled (ProxyState.java:65)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at foreach (ObserverPairList.java:109)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at notifyQueryFinished (ProxyState.java:132)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onQueryFinished (ProxyState.java:199)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at notifyFrontEnd (PendingRow.java:244)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at access$000 (PendingRow.java:20)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onChange (PendingRow.java:48)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onChange (PendingRow.java:45)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onChange (ObservableCollection.java:39)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onChange (ObservableCollection.java:20)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onCalled (ObservableCollection.java:64)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at onCalled (ObservableCollection.java:54)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at foreach (ObserverPairList.java:109)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at notifyChangeListeners (OsResults.java:451)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at nativePollOnce (MessageQueue.java:-2)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at next (MessageQueue.java:323)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at loop (Looper.java:135)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at main (ActivityThread.java:5443)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at invoke (Method.java:-2)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at run (ZygoteInit.java:728)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at main (ZygoteInit.java:618)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410] 
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]     in call to NewLocalRef
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]     from void android.os.MessageQueue.nativePollOnce(long, int)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410] "main" prio=5 tid=1 Runnable
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x743772a0 self=0xb75def28
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=24568 nice=0 cgrp=default sched=0/0 handle=0xb6f38b34
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 1098009133 178187438 936 ) utm=91 stm=18 core=1 HZ=100
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   | stack=0xbe5fc000-0xbe5fe000 stackSize=8MB
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 0035ca4d  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+116)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 0033d8a3  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+138)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0024f759  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+760)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 0024fdf7  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+54)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 000fc0f3  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+30)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 00100fcf  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.95+5054)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 00106399  /system/lib/libart.so (_ZN3art8CheckJNI11NewLocalRefEP7_JNIEnvP8_jobject+376)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 0006944b  /data/app/org.fossasia.openevent-2/lib/arm/librealm-jni.so (???)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 0006594d  /data/app/org.fossasia.openevent-2/lib/arm/librealm-jni.so (???)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 00090e71  /data/app/org.fossasia.openevent-2/lib/arm/librealm-jni.so (???)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 00082ead  /data/app/org.fossasia.openevent-2/lib/arm/librealm-jni.so (???)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #11 pc 0009fdfd  /data/app/org.fossasia.openevent-2/lib/arm/librealm-jni.so (???)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #12 pc 000a06f1  /data/app/org.fossasia.openevent-2/lib/arm/librealm-jni.so (???)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #13 pc 00012f4f  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+530)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #14 pc 0001301f  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+130)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #15 pc 00083ed1  /system/lib/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+22)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   native: #16 pc 00000585  /system/framework/arm/boot.oat (Java_android_os_MessageQueue_nativePollOnce__JI+96)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at android.os.MessageQueue.nativePollOnce(Native method)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at android.os.MessageQueue.next(MessageQueue.java:323)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Looper.loop(Looper.java:135)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread.main(ActivityThread.java:5443)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.reflect.Method.invoke!(Native method)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
05-16 11:52:27.320 24568-24568/org.fossasia.openevent A/art: art/runtime/java_vm_ext.cc:410] 
```

**Gif of the issue**

![videotogif_2018 05 16_11 48 27](https://user-images.githubusercontent.com/16715499/40099909-ab598c7c-58ff-11e8-8678-ce0355abe401.gif)

**Would you like to work on the issue?**

Yes

**Comment by simarsingh24** [comment]
@nikit19  could you confirm if this is happening on your device too?

**Comment by nikit19** [comment]
Works fine in my device. I am using Android 7.0
What about you ?
It could be an API version specific problem

**Comment by simarsingh24** [comment]
@nikit19 In that case, closing this issue for now!
